name: Build Deploy Simple Web Server

on:


jobs:
  demo-parallelism:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Nothing meaninful'
      run: 'echo Silly V'
      
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY}}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to cloud build'
      run: gcloud builds submit --tag gcr.io/alert-arbor-261117/simple-webserver
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy simple-webserver --image=gcr.io/alert-arbor-261117/simple-webserver:latest --region=us-central1 --allow-unauthenticated
